import * as THREE from "three";

export type Layer3D = { id: string; group: string; color: number; opacity: number; builder: string; note: string };
export const EVERY_FILE_3D_LAYERS: Record<string, Layer3D> = {
  buildings: { id: "buildings", group: "buildings", color: 0xe2e8f0, opacity: 1, builder: "buildBuildings", note: "Extrude + wardDamage + Bathtub" },
  google_open_buildings_chennai: { id: "google_open_buildings_chennai", group: "buildings", color: 0xd6e0ec, opacity: 0.9, builder: "buildBuildings", note: "Google 1.8B addl footprints — same extrude, alt mat" },
  chennai_building_heights_lidar: { id: "chennai_building_heights_lidar", group: "buildings", color: 0xcbd5e1, opacity: 1, builder: "buildBuildings", note: "nDSM height drives extrude h=height_m" },
  chennai_heritage: { id: "chennai_heritage", group: "buildings", color: 0x8b7355, opacity: 0.95, builder: "buildBuildings", note: "Heritage 62 — brass emissive, protected" },
  highway: { id: "highway", group: "roads", color: 0xfacc15, opacity: 0.72, builder: "buildRoads", note: "LineBasic, velocity_field teal" },
  chennai_metro_rail: { id: "chennai_metro_rail", group: "roads", color: 0x06b6d4, opacity: 0.85, builder: "buildRoads", note: "Elevated 12m, flood clearance 4.5m — dashed" },
  chennai_railway_stations: { id: "chennai_railway_stations", group: "roads", color: 0x475569, opacity: 0.9, builder: "buildRoads", note: "SR 32 — station markers" },
  chennai_bus_stops: { id: "chennai_bus_stops", group: "roads", color: 0xf59e0b, opacity: 0.8, builder: "buildInfrastructureMarkers", note: "MTC 2,800 — tiny cylinders" },
  chennai_bus_depots: { id: "chennai_bus_depots", group: "roads", color: 0xea580c, opacity: 0.85, builder: "buildInfrastructureMarkers", note: "36 depots — flood_prone red" },
  natural_water: { id: "natural_water", group: "waterways", color: 0x0284c7, opacity: 0.5, builder: "buildNaturalWater", note: "Polygon water OSM 555" },
  waterway: { id: "waterway", group: "waterways", color: 0x0284c7, opacity: 0.85, builder: "buildWaterways", note: "Adyar/Cooum/Kosasthalaiyar 12 + drainage" },
  chennai_drainage: { id: "chennai_drainage", group: "waterways", color: 0x0e7490, opacity: 0.9, builder: "buildWaterways", note: "SWD 5 + capacity" },
  chennai_swd_stormwater_drain: { id: "chennai_swd_stormwater_drain", group: "waterways", color: 0x0c6580, opacity: 0.9, builder: "buildWaterways", note: "GOS — real SWD" },
  chennai_canals_detailed: { id: "chennai_canals_detailed", group: "waterways", color: 0x0e7490, opacity: 0.85, builder: "buildWaterways", note: "34 canals" },
  chennai_sewage_network: { id: "chennai_sewage_network", group: "waterways", color: 0x475569, opacity: 0.6, builder: "buildWaterways", note: "CMWSSB 1,200km — dashed" },
  chennai_sewage_outfalls: { id: "chennai_sewage_outfalls", group: "waterways", color: 0x1e3a5a, opacity: 0.9, builder: "buildInfrastructureMarkers", note: "22 outfalls" },
  chennai_pumping_stations: { id: "chennai_pumping_stations", group: "waterways", color: 0x10b981, opacity: 0.9, builder: "buildInfrastructureMarkers", note: "68 pumps — pulsing" },
  chennai_tide_gauge: { id: "chennai_tide_gauge", group: "water", color: 0x06b6d4, opacity: 1, builder: "waterLevel", note: "Ennore/Marina surge +0.11m drives water.y" },
  chennai_tide_forecast: { id: "chennai_tide_forecast", group: "water", color: 0x0891b2, opacity: 1, builder: "waterLevel", note: "INCOIS 7-day forecast" },
  chennai_storm_surge_zones: { id: "chennai_storm_surge_zones", group: "water", color: 0xef4444, opacity: 0.25, builder: "buildFloodMask", note: "INCOIS 6 RP — red mask" },
  chennai_flood_walls_bunds: { id: "chennai_flood_walls_bunds", group: "waterways", color: 0x57534e, opacity: 0.9, builder: "buildWaterways", note: "48km WRD — wall" },
  chennai_ward_flooddepth_2015: { id: "chennai_ward_flooddepth_2015", group: "wards", color: 0xe63946, opacity: 0.45, builder: "buildWards", note: "200 wards depth — choropleth" },
  chennai_flood_hazard_zones_gcc: { id: "chennai_flood_hazard_zones_gcc", group: "wards", color: 0xe63946, opacity: 0.35, builder: "buildFloodMask", note: "38MiB High/Mod/Low — mask" },
  chennai_flow_5yr_return: { id: "chennai_flow_5yr_return", group: "wards", color: 0xfacc15, opacity: 0.2, builder: "buildFloodMask", note: "5yr RP" },
  chennai_flow_100yr_return: { id: "chennai_flow_100yr_return", group: "wards", color: 0x991b1b, opacity: 0.25, builder: "buildFloodMask", note: "100yr RP" },
  chennai_lulc: { id: "chennai_lulc", group: "terrain", color: 0x8fa998, opacity: 0.35, builder: "terrainTint", note: "Bhuvan impervious → terrain roughness" },
  chennai_soil: { id: "chennai_soil", group: "terrain", color: 0xa89078, opacity: 0.3, builder: "terrainTint", note: "NBSS CN factor → terrain mat" },
  chennai_groundwater: { id: "chennai_groundwater", group: "terrain", color: 0x0ea5e9, opacity: 0.4, builder: "buildInfrastructureMarkers", note: "CGWB 24 wells — depth sphere" },
  chennai_soil_moisture: { id: "chennai_soil_moisture", group: "terrain", color: 0x10b981, opacity: 0.3, builder: "terrainMoisture", note: "SMAP 9km — terrain emissive" },
  chennai_parks_waterbodies: { id: "chennai_parks_waterbodies", group: "vegetation", color: 0x22c55e, opacity: 0.5, builder: "buildVegetation", note: "42 parks/lakes — retention green" },
  chennai_wetlands: { id: "chennai_wetlands", group: "vegetation", color: 0x16a34a, opacity: 0.45, builder: "buildVegetation", note: "Pallikaranai 1,200ha" },
  chennai_mangroves: { id: "chennai_mangroves", group: "vegetation", color: 0x15803d, opacity: 0.55, builder: "buildVegetation", note: "Ennore 120ha — dense" },
  chennai_tree_census_2023: { id: "chennai_tree_census_2023", group: "vegetation", color: 0x4ade80, opacity: 0.6, builder: "buildTreeBillboards", note: "2.3L trees — billboards" },
  chennai_contours_1m: { id: "chennai_contours_1m", group: "terrain", color: 0x57534e, opacity: 0.6, builder: "buildContours", note: "1m contours — Line2" },
  chennai_watershed_boundaries: { id: "chennai_watershed_boundaries", group: "terrain", color: 0x44403c, opacity: 0.18, builder: "buildFloodMask", note: "D8 11 basins — outline" },
  chennai_land_subsidence: { id: "chennai_land_subsidence", group: "terrain", color: 0xdc2626, opacity: 0.5, builder: "buildInfrastructureMarkers", note: "InSAR mm/yr — red pulse" },
  chennai_drone_adyar_dsm_10cm: { id: "chennai_drone_adyar_dsm_10cm", group: "terrain", color: 0x111210, opacity: 0.15, builder: "terrainDetail", note: "10cm DSM — detail displacement" },
  chennai_bathymetry_adayar: { id: "chennai_bathymetry_adayar", group: "terrain", color: 0x0c4a6e, opacity: 0.4, builder: "terrainBathy", note: "Sonar estuary — deepen" },
  chennai_slums_vulnerability: { id: "chennai_slums_vulnerability", group: "buildings", color: 0x991b1b, opacity: 0.9, builder: "buildingTint", note: "120 slums — vulnerability red tint" },
  chennai_slums_locations: { id: "chennai_slums_locations", group: "buildings", color: 0x7f1d1d, opacity: 0.85, builder: "buildingTint", note: "Slum locations — same" },
  chennai_population_grid_100m: { id: "chennai_population_grid_100m", group: "buildings", color: 0xf59e0b, opacity: 0.3, builder: "buildingHeat", note: "WorldPop 100m — heat" },
  chennai_land_parcels: { id: "chennai_land_parcels", group: "terrain", color: 0xa3a3a3, opacity: 0.12, builder: "buildFloodMask", note: "CMDA 45k — parcel overlay" },
  chennai_hospitals_relief: { id: "chennai_hospitals_relief", group: "infrastructure", color: 0x10b981, opacity: 0.95, builder: "buildInfrastructureMarkers", note: "78 hospitals — green cross" },
  chennai_evacuation_routes: { id: "chennai_evacuation_routes", group: "roads", color: 0x22c55e, opacity: 0.9, builder: "buildEvacuationRoutes", note: "12 routes — dashed green" },
  chennai_schools_shelters: { id: "chennai_schools_shelters", group: "infrastructure", color: 0x0ea5e9, opacity: 0.9, builder: "buildInfrastructureMarkers", note: "212 schools — shelter icon" },
  chennai_cyclone_tracks: { id: "chennai_cyclone_tracks", group: "infrastructure", color: 0x7c3aed, opacity: 0.85, builder: "buildCycloneTracks", note: "BoB cyclones 2000-25 — purple" },
  chennai_sentinel1_flood_extent: { id: "chennai_sentinel1_flood_extent", group: "water", color: 0x1e40af, opacity: 0.28, builder: "buildFloodMask", note: "Sentinel-1 264km² 2015" },
  chennai_historical_floods_2016_2024: { id: "chennai_historical_floods_2016_2024", group: "water", color: 0x1e3a8a, opacity: 0.22, builder: "buildFloodMask", note: "2016-24 6 events" },
  chennai_2015_inundation: { id: "chennai_2015_inundation", group: "water", color: 0x991b1b, opacity: 0.32, builder: "buildFloodMask", note: "2015 inundation NRSC" },
  chennai_2015_hotspots: { id: "chennai_2015_hotspots", group: "infrastructure", color: 0xe63946, opacity: 0.9, builder: "buildHotspots", note: "327 hotspots — cylinders" },
  rainfall_stations: { id: "rainfall_stations", group: "infrastructure", color: 0x111210, opacity: 0.9, builder: "buildRainfallStations", note: "IMD 8 — gauge" },
};

export function get3DContribution(id: string): Layer3D | null { return EVERY_FILE_3D_LAYERS[id] || null; }
export function groupForDataset(id: string): string { return EVERY_FILE_3D_LAYERS[id]?.group || "infrastructure"; }
export function all3DIds(): string[] { return Object.keys(EVERY_FILE_3D_LAYERS); }
