-- FLOIN — canonical PostGIS schema (the shareable contract for this database).
--
-- Idempotent: safe to re-run against an existing database.
-- Used in two places, so the two paths can never drift:
--   1. docker compose up -d  -> mounted as /docker-entrypoint-initdb.d/10-floin-schema.sql
--   2. db/Dockerfile         -> COPY ed into the prebuilt ghcr.io image
--
-- Contract with the app (do not rename `geom`):
--   app/api/location/query/route.ts:90 and app/api/location/features/route.ts:14 run
--     SELECT ST_AsGeoJSON(geom)::json AS geometry, row_to_json(t) - 'geom' AS props
--       FROM <table> t
--      WHERE ST_Intersects(geom, ST_MakeEnvelope($1,$2,$3,$4,4326))
--   Vector tables therefore expose a column literally named `geom` in SRID 4326.
--
-- Geometry columns are declared generic `geometry(Geometry,4326)` on purpose:
-- data/vectors mixes Polygon/MultiPolygon and — per the note in
-- app/api/location/query/route.ts:55-57 — GeometryCollection is common in the GCC KML
-- exports. A narrower typmod would reject those rows. Dominant type per layer is
-- recorded in floin_expected_layers.geom_type instead.

CREATE EXTENSION IF NOT EXISTS postgis;

-- ---------------------------------------------------------------------------
-- 1. Registry — what this database is and what it is supposed to contain
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS floin_meta (
  key        text PRIMARY KEY,
  value      text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO floin_meta (key, value) VALUES
  ('schema_version', '1'),
  ('crs',            'EPSG:4326'),
  ('generator',      'db/schema.sql'),
  ('data_root',      'data/vectors + data/rasters (see docs/DB_SHARING.md)')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();

-- Expected layers — mirrors scripts/load_postgis.py and db/bootstrap-load.sh.
-- `scripts/db_share.py verify` diffs this against the live database, so a stale
-- dump or a skipped file shows up immediately instead of silently returning 0 rows.
CREATE TABLE IF NOT EXISTS floin_expected_layers (
  layer_name  text PRIMARY KEY,
  layer_role  text NOT NULL CHECK (layer_role IN ('vector', 'raster')),
  source_file text NOT NULL,
  geom_type   text NOT NULL
);

INSERT INTO floin_expected_layers (layer_name, layer_role, source_file, geom_type) VALUES
  ('buildings',                   'vector', 'buildings.geojson',                   'Polygon/MultiPolygon'),
  ('highway',                     'vector', 'highway.geojson',                     'LineString'),
  ('natural_water',               'vector', 'natural_water.geojson',               'Polygon'),
  ('waterway',                    'vector', 'waterway.geojson',                    'LineString'),
  ('rainfall_stations',           'vector', 'rainfall_stations.geojson',           'Point'),
  ('chennai2015_inundation',      'vector', 'chennai2015_inundation.geojson',      'Polygon/MultiPolygon'),
  ('chennai2015_hotspots',        'vector', 'chennai2015_hotspots.geojson',        'Point'),
  ('chennai2015_flooded_streets', 'vector', 'chennai2015_flooded_streets.geojson', 'LineString'),
  ('dem',                         'raster', 'rasters_COP30/DEM.tif',               'raster'),
  ('flow_direction',              'raster', 'Flow_Direction.tif',                  'raster'),
  ('flow_accumulation',           'raster', 'Flow_Accumulation.tif',               'raster'),
  ('watershed',                   'raster', 'Watershed.tif',                       'raster'),
  ('streams',                     'raster', 'Streams.tif',                         'raster')
ON CONFLICT (layer_name) DO UPDATE SET
  layer_role  = EXCLUDED.layer_role,
  source_file = EXCLUDED.source_file,
  geom_type   = EXCLUDED.geom_type;

-- ---------------------------------------------------------------------------
-- 2. Vector layer skeletons — empty, typed, indexed.
--    scripts/load_postgis.py / db/bootstrap-load.sh fill these with
--    `ogr2ogr … -lco GEOMETRY_NAME=geom -lco SPATIAL_INDEX=GIST`, which replaces
--    the table in place (same `geom` column, so the API contract holds either way).
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  layer text;
  vector_layers text[] := ARRAY[
    'buildings', 'highway', 'natural_water', 'waterway', 'rainfall_stations',
    'chennai2015_inundation', 'chennai2015_hotspots', 'chennai2015_flooded_streets'
  ];
BEGIN
  FOREACH layer IN ARRAY vector_layers LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS public.%I ('
      '  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
      '  geom geometry(Geometry, 4326) NOT NULL,'
      '  loaded_at timestamptz NOT NULL DEFAULT now()'
      ')', layer);
    EXECUTE format(
      'CREATE INDEX IF NOT EXISTS %I ON public.%I USING GIST (geom)',
      layer || '_geom_gix', layer);
    EXECUTE format(
      'COMMENT ON TABLE public.%I IS %L',
      layer, 'FLOIN vector layer — ingested from data/vectors via ogr2ogr, EPSG:4326, geometry column "geom"');
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 3. Ingest log — one row per load, written by the loader / image bootstrap
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS floin_ingest_log (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name    text NOT NULL,
  layer_role    text NOT NULL CHECK (layer_role IN ('vector', 'raster')),
  source_file   text,
  feature_count bigint,
  loader        text,
  loaded_at     timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 4. Report view — what `npm run db:verify` and the DB CI job read
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW floin_db_report AS
SELECT e.layer_name,
       e.layer_role,
       e.geom_type                  AS expected_geom_type,
       g.type                       AS actual_geom_type,
       g.srid,
       (g.f_table_name IS NOT NULL) AS table_present
  FROM floin_expected_layers e
  LEFT JOIN geometry_columns g
    ON g.f_table_schema = 'public'
   AND g.f_table_name   = e.layer_name
 ORDER BY e.layer_role, e.layer_name;

-- ---------------------------------------------------------------------------
-- 5. Shared-DB hygiene — a restored dump does not carry ownership. If the
--    application role exists (see .env.example: user `floin`), let it read
--    everything without taking ownership of the restored objects.
-- ---------------------------------------------------------------------------

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'floin') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA public TO floin';
    EXECUTE 'GRANT SELECT ON ALL TABLES IN SCHEMA public TO floin';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO floin';
    RAISE NOTICE 'floin role present - granted read access to public schema';
  ELSE
    RAISE NOTICE 'floin role absent - skipped grants (create it, then re-run db/schema.sql)';
  END IF;
END $$;
